# Generated by Django 5.0.7 on 2024-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='gogo@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Gogo', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0712345678', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
